export enum MainActionTypes {
	MAIN_CHECK = 'MAIN.CHECK',
	MAIN_SWITCH_NETWORK = 'MAIN.SWITCH_NETWORK',
	SET_STATE = 'MAIN.SET_STATE',
	LOAD_DATA = 'MAIN.LOAD_DATA',
	READ_APPROVALS = 'MAIN.READ_APPROVALS',
	READ_COINGECK_PRICES = 'MAIN.READ_COINGECK_PRICES',
	READ_BALANCES = 'MAIN.READ_BALANCES',
	ADD_REWARD = 'MAIN.ADD_REWARD',
	UPDATE_HISTORY = 'MAIN.UPDATE_HISTORY',

	START_FLOW = 'MAIN.START_FLOW',
	STOP_FLOW = 'MAIN.STOP_FLOW',
	DOWNGRADE = 'MAIN.DOWNGRADE',
	APPROVE = 'MAIN.APPROVE',
	UPGRADE = 'MAIN.UPGRADE',

	SELECT_UPGRADE_COIN = 'SELECT_UPGRADE_COIN',
	SELECT_DOWNGRADE_COIN = 'SELECT_DOWNGRADE_COIN',
	SHOW_TYPE_TOKEN_LIST = 'SHOW_TYPE_TOKEN_LIST',
	LOAD_READ_ONLY_DATA = 'LOAD_READ_ONLY_DATA',
	CONNECT_WEB3_MODAL = 'CONNECT_WEB3_MODAL',
}
