import Web3 from 'web3';
import { Coin } from '../../constants/coins';

type FlowQueryType = {
	flowKey: string;
	flowsReceived: number;
	flowsOwned: string;
	totalFlows: number;
	placeholder: string;
	subsidyRate: { perso: number; total: number; endDate: string };
	streamedSoFar?: number;
	streamedSoFarTimestamp?: number;
	receivedSoFar?: number;
	receivedSoFarTimestamp?: number;
};

export type MainState = {
	web3: Web3;
	readWeb3: Web3;
	address: string;
	balances?: { [key: string]: string };
	coingeckoPrices?: { [key: string]: number };
	hasUsdcApprove?: boolean;
	hasDaiApprove?: boolean;
	hasMkrApprove?: boolean;
	hasWethApprove?: boolean;
	hasWbtcApprove?: boolean;
	hasMaticApprove?: boolean;
	hasSushiApprove?: boolean;
	hasIdleApprove?: boolean;
	hasIbAlluoUSDApprove?: boolean;
	hasIbAlluoETHApprove?: boolean;
	hasIbAlluoBTCApprove?: boolean;
	apy?: number;
	rewardsApy?: number;
	feesApy?: number;
	usdcRicFlowQuery?: FlowQueryType;
	usdcxibAlluoUSDFlowQuery?: FlowQueryType;
	usdcSlpEthFlowQuery?: FlowQueryType;
	usdcWethFlowQuery?: FlowQueryType;
	daiMkrFlowQuery?: FlowQueryType;
	mkrDaiFlowQuery?: FlowQueryType;
	usdcMkrFlowQuery?: FlowQueryType;
	mkrUsdcFlowQuery?: FlowQueryType;
	daiMaticFlowQuery?: FlowQueryType;
	maticDaiFlowQuery?: FlowQueryType;
	usdcMaticFlowQuery?: FlowQueryType;
	maticUsdcFlowQuery?: FlowQueryType;
	daiEthFlowQuery?: FlowQueryType;
	ethDaiFlowQuery?: FlowQueryType;
	usdcWbtcFlowQuery?: FlowQueryType;
	wethUsdcFlowQuery?: FlowQueryType;
	wbtcUsdcFlowQuery?: FlowQueryType;
	usdcIdleFlowQuery?: FlowQueryType;
	twoWayusdcWethFlowQuery?: FlowQueryType;
	twoWaywethUsdcFlowQuery?: FlowQueryType;
	twoWaywbtcUsdcFlowQuery?: FlowQueryType;
	twoWayusdcWbtcFlowQuery?: FlowQueryType;
	twoWayDaiWethFlowQuery?: FlowQueryType;
	twoWayWethDaiFlowQuery?: FlowQueryType;
	twoWayRicUsdcFlowQuery?: FlowQueryType;
	twoWayUsdcRicFlowQuery?: FlowQueryType;
	twoWayMaticUsdcFlowQuery?: FlowQueryType;
	twoWayUsdcMaticFlowQuery?: FlowQueryType;
	twoWayMaticDaiFlowQuery?: FlowQueryType;
	twoWayDaiMaticFlowQuery?: FlowQueryType;
	twoWayWbtcDaiFlowQuery?: FlowQueryType;
	twoWayDaiWbtcFlowQuery?: FlowQueryType;
	twoWayIbUsdIbEthFlowQuery?: FlowQueryType;
	twoWayIbEthIbUsdFlowQuery?: FlowQueryType;
	twoWayIbUsdIbBTCFlowQuery?: FlowQueryType;
	twoWayIbBTCIbUsdFlowQuery?: FlowQueryType;
	isLoadingDowngrade: boolean;
	isLoadingUpgrade: boolean;
	isLoading: boolean;
	selectedDowngradeCoin: Coin;
	selectedUpgradeCoin: Coin;
	coinType: Coin;
	isReadOnly: boolean;
	referralId?: string;
};
