export const launchpadABI = [
	{
		inputs: [
			{ internalType: 'contract ISuperfluid', name: 'host', type: 'address' },
			{
				internalType: 'contract IConstantFlowAgreementV1',
				name: 'cfa',
				type: 'address',
			},
			{
				internalType: 'contract IInstantDistributionAgreementV1',
				name: 'ida',
				type: 'address',
			},
			{ internalType: 'string', name: 'registrationKey', type: 'string' },
		],
		stateMutability: 'nonpayable',
		type: 'constructor',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: 'previousOwner',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'address',
				name: 'newOwner',
				type: 'address',
			},
		],
		name: 'OwnershipTransferred',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: 'address',
				name: 'from',
				type: 'address',
			},
			{ indexed: false, internalType: 'int96', name: 'newRate', type: 'int96' },
			{
				indexed: false,
				internalType: 'int96',
				name: 'totalInflow',
				type: 'int96',
			},
		],
		name: 'UpdatedStream',
		type: 'event',
	},
	{
		inputs: [
			{
				internalType: 'contract ISuperToken',
				name: '_superToken',
				type: 'address',
			},
			{ internalType: 'address', name: '_agreementClass', type: 'address' },
			{ internalType: 'bytes32', name: '', type: 'bytes32' },
			{ internalType: 'bytes', name: '_agreementData', type: 'bytes' },
			{ internalType: 'bytes', name: '', type: 'bytes' },
			{ internalType: 'bytes', name: '_ctx', type: 'bytes' },
		],
		name: 'afterAgreementCreated',
		outputs: [{ internalType: 'bytes', name: 'newCtx', type: 'bytes' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'contract ISuperToken',
				name: '_superToken',
				type: 'address',
			},
			{ internalType: 'address', name: '_agreementClass', type: 'address' },
			{ internalType: 'bytes32', name: '', type: 'bytes32' },
			{ internalType: 'bytes', name: '_agreementData', type: 'bytes' },
			{ internalType: 'bytes', name: '', type: 'bytes' },
			{ internalType: 'bytes', name: '_ctx', type: 'bytes' },
		],
		name: 'afterAgreementTerminated',
		outputs: [{ internalType: 'bytes', name: 'newCtx', type: 'bytes' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'contract ISuperToken',
				name: '_superToken',
				type: 'address',
			},
			{ internalType: 'address', name: '_agreementClass', type: 'address' },
			{ internalType: 'bytes32', name: '', type: 'bytes32' },
			{ internalType: 'bytes', name: '_agreementData', type: 'bytes' },
			{ internalType: 'bytes', name: '', type: 'bytes' },
			{ internalType: 'bytes', name: '_ctx', type: 'bytes' },
		],
		name: 'afterAgreementUpdated',
		outputs: [{ internalType: 'bytes', name: 'newCtx', type: 'bytes' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'contract ISuperToken', name: '', type: 'address' },
			{ internalType: 'address', name: '', type: 'address' },
			{ internalType: 'bytes32', name: '', type: 'bytes32' },
			{ internalType: 'bytes', name: '', type: 'bytes' },
			{ internalType: 'bytes', name: '', type: 'bytes' },
		],
		name: 'beforeAgreementCreated',
		outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'contract ISuperToken', name: '', type: 'address' },
			{ internalType: 'address', name: '', type: 'address' },
			{ internalType: 'bytes32', name: '', type: 'bytes32' },
			{ internalType: 'bytes', name: '', type: 'bytes' },
			{ internalType: 'bytes', name: '', type: 'bytes' },
		],
		name: 'beforeAgreementTerminated',
		outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'contract ISuperToken', name: '', type: 'address' },
			{ internalType: 'address', name: '', type: 'address' },
			{ internalType: 'bytes32', name: '', type: 'bytes32' },
			{ internalType: 'bytes', name: '', type: 'bytes' },
			{ internalType: 'bytes', name: '', type: 'bytes' },
		],
		name: 'beforeAgreementUpdated',
		outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'streamer', type: 'address' }],
		name: 'closeStream',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'distribute',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'streamer', type: 'address' }],
		name: 'emergencyCloseStream',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'emergencyDrain',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getFeeRate',
		outputs: [{ internalType: 'uint128', name: '', type: 'uint128' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'uint32', name: 'index', type: 'uint32' },
			{ internalType: 'address', name: 'streamer', type: 'address' },
		],
		name: 'getIDAShares',
		outputs: [
			{ internalType: 'bool', name: 'exist', type: 'bool' },
			{ internalType: 'bool', name: 'approved', type: 'bool' },
			{ internalType: 'uint128', name: 'units', type: 'uint128' },
			{ internalType: 'uint256', name: 'pendingDistribution', type: 'uint256' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getInputToken',
		outputs: [{ internalType: 'contract ISuperToken', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getLastDistributionAt',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getOutputIndexId',
		outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getOutputRate',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getOutputToken',
		outputs: [{ internalType: 'contract ISuperToken', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getOwner',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getSharePrice',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'streamer', type: 'address' }],
		name: 'getStreamRate',
		outputs: [{ internalType: 'int96', name: 'requesterFlowRate', type: 'int96' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getTotalInflow',
		outputs: [{ internalType: 'int96', name: '', type: 'int96' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'contract ISuperToken',
				name: 'inputToken',
				type: 'address',
			},
			{
				internalType: 'contract ISuperToken',
				name: 'outputToken',
				type: 'address',
			},
			{ internalType: 'address', name: 'originator', type: 'address' },
			{ internalType: 'address', name: 'beneficiary', type: 'address' },
			{ internalType: 'uint256', name: 'outputRate', type: 'uint256' },
			{ internalType: 'uint128', name: 'feeRate', type: 'uint128' },
		],
		name: 'initialize',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'isAppJailed',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'owner',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'renounceOwnership',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint128', name: 'feeRate', type: 'uint128' }],
		name: 'setFeeRate',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
		name: 'transferOwnership',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
];
