export enum BanksActionTypes {
  SET_STATE = 'BANKS.SET_STATE',
  LOAD_DATA = 'BANKS.LOAD_DATA',
  MAKE_DEPOSIT = 'BANKS.MAKE_DEPOSIT',
  MAKE_BORROW = 'BANKS.MAKE_BORROW',
  APPROVE_TOKEN = 'BANKS.APPROVE_TOKEN',
  MAKE_TRANSACTION = 'BANKS.MAKE_TRANSACTION',
}
