import {
  DAIAddress,
  DAIxAddress,
  daixEthxExchangeAddress,
  daixMaticxExchangeAddress,
  daixMkrxExchangeAddress,
  ethxDaixExchangeAddress,
  hostAddress,
  idaAddress,
  IDLEAddress,
  IDLExAddress,
  MATICxAddress,
  maticxDaixExchangeAddress,
  maticxUsdcxExchangeAddress,
  MKRAddress,
  MKRxAddress,
  mkrxDaixExchangeAddress,
  mkrxUsdcxExchangeAddress,
  rexReferralAddress,
  RICAddress,
  rickosheaAppAddress,
  SUSHIAddress,
  SUSHIxAddress,
  twoWayWETHMarketAddress,
  twoWayMarketWBTCAddress,
  USDCAddress,
  USDCxAddress,
  usdcxEthSlpxExchangeAddress,
  usdcxIdleExchangeAddress,
  usdcxMaticxExchangeAddress,
  usdcxMkrxExchangeAddress,
  usdcxRicExchangeAddress,
  usdcxWbtcxExchangeAddress,
  usdcxWethxExchangeAddress,
  WBTCAddress,
  WBTCxAddress,
  wbtcxUsdcxExchangeAddress,
  WETHAddress,
  WETHxAddress,
  wethxUsdcxExchangeAddress,
  twoWayMarketDAIWETHAddress,
  twoWayMarketRICUSDCAddress,
  twoWayMarketMATICUSDCAddress,
  twoWayMarketMATICDAIAddress, twoWayMarketWBTCDAIAddress,

} from 'constants/polygon_config';

export enum ExchangeKeys {
  'DAI_ETH' = 'twoWayDaiWeth',
  'DAI_MATIC' = 'daiMatic',
  'DAI_MKR' = 'daiMkr',
  'ETH_DAI' = 'twoWayWethDai',
  'MATIC_DAI' = 'maticDai',
  'MATIC_USDC' = 'maticUsdc',
  'MKR_DAI' = 'mkrDai',
  'MKR_USDC' = 'mkrUsdc',
  'USDC_ETH_SLP' = 'usdcEthSlp',
  'USDC_IDLE' = 'usdcIdle',
  'USDC_MATIC' = 'usdcMatic',
  'USDC_MKR' = 'usdcMkr',
  'USDC_RIC' = 'usdcRic',
  'USDC_WBTC' = 'twoWayusdcWbtc',
  'USDC_WETH' = 'twoWayusdcWeth',
  'WBTC_USDC' = 'twoWaywbtcUsdc',
  'WETH_USDC' = 'twoWaywethUsdc',
  'TWO_USDC_RIC' = 'twoWayUsdcRic',
  'TWO_RIC_USDC' = 'twoWayRicUsdc',
  'TWO_WAY_MATIC_USDC' = 'twoWayMaticUsdc',
  'TWO_WAY_USDC_MATIC' = 'twoWayUsdcMatic',
  'TWO_WAY_MATIC_DAI' = 'twoWayMaticDai',
  'TWO_WAY_DAI_MATIC' = 'twoWayDaiMatic',
  'TWO_WAY_WBTC_DAI' = 'twoWayWbtcDai',
  'TWO_WAY_DAI_WBTC' = 'twoWayDaiWbtc',
  'MATICx' = 'maticx',
  'MKRx' = 'mkrx',
  'MKR' = 'mkr',
  'DAIx' = 'daix',
  'DAI' = 'dai',
  'USDCx' = 'usdcx',
  'USDC' = 'usdc',
  'WETHx' = 'wethx',
  'WETH' = 'weth',
  'WBTCx' = 'wbtcx',
  'WBTC' = 'wbtc',
  'HOST' = 'host',
  'IDA' = 'ida',
  'RICapp' = 'ricApp',
  'RIC' = 'ric',
  'SUSHIx' = 'sushix',
  'SUSHI' = 'sushi',
  'IDLEx' = 'idlex',
  'IDLE' = 'idle',
  'Referral' = 'referral',
}

export const getExchangeAddressFromKey = (exchangeKey: ExchangeKeys) => {
  const addresses = {
    daiEth: daixEthxExchangeAddress,
    daiMatic: daixMaticxExchangeAddress,
    daiMkr: daixMkrxExchangeAddress,
    ethDai: ethxDaixExchangeAddress,
    maticDai: maticxDaixExchangeAddress,
    maticUsdc: maticxUsdcxExchangeAddress,
    mkrDai: mkrxDaixExchangeAddress,
    mkrUsdc: mkrxUsdcxExchangeAddress,
    usdcEthSlp: usdcxEthSlpxExchangeAddress,
    usdcIdle: usdcxIdleExchangeAddress,
    usdcMatic: usdcxMaticxExchangeAddress,
    usdcMkr: usdcxMkrxExchangeAddress,
    usdcRic: usdcxRicExchangeAddress,
    usdcWbtc: usdcxWbtcxExchangeAddress,
    usdcWeth: usdcxWethxExchangeAddress,
    wbtcUsdc: wbtcxUsdcxExchangeAddress,
    wethUsdc: wethxUsdcxExchangeAddress,
    maticx: MATICxAddress,
    mkrx: MKRxAddress,
    mkr: MKRAddress,
    daix: DAIxAddress,
    dai: DAIAddress,
    usdcx: USDCxAddress,
    usdc: USDCAddress,
    wethx: WETHxAddress,
    weth: WETHAddress,
    wbtcx: WBTCxAddress,
    wbtc: WBTCAddress,
    host: hostAddress,
    ida: idaAddress,
    ricApp: rickosheaAppAddress,
    ric: RICAddress,
    sushix: SUSHIxAddress,
    sushi: SUSHIAddress,
    idlex: IDLExAddress,
    idle: IDLEAddress,
    referral: rexReferralAddress,
    twoWayusdcWeth: twoWayWETHMarketAddress,
    twoWaywethUsdc: twoWayWETHMarketAddress,
    twoWaywbtcUsdc: twoWayMarketWBTCAddress,
    twoWayusdcWbtc: twoWayMarketWBTCAddress,
    twoWayDaiWeth: twoWayMarketDAIWETHAddress,
    twoWayWethDai: twoWayMarketDAIWETHAddress,
    twoWayRicUsdc: twoWayMarketRICUSDCAddress,
    twoWayUsdcRic: twoWayMarketRICUSDCAddress,
    twoWayMaticUsdc: twoWayMarketMATICUSDCAddress,
    twoWayUsdcMatic: twoWayMarketMATICUSDCAddress,
    twoWayMaticDai: twoWayMarketMATICDAIAddress,
    twoWayDaiMatic: twoWayMarketMATICDAIAddress,
    twoWayWbtcDai: twoWayMarketWBTCDAIAddress,
    twoWayDaiWbtc: twoWayMarketWBTCDAIAddress,
  };

  return addresses[exchangeKey];
};
